/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kasirapp.view;

import com.kasirapp.controller.MenuController;
import com.kasirapp.model.MenuItem;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Izzat Fauzan
 */
public class FormMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenu.class.getName());
    private static final Dimension UKURAN_FORM = new Dimension(1000, 740);
    private static final Color WARNA_LATAR = new Color(250, 244, 235);
    private static final Color WARNA_PANEL = new Color(255, 251, 245);
    private static final Color WARNA_COKELAT_TUA = new Color(78, 43, 18);
    private static final Color WARNA_BORDER = new Color(218, 190, 154);
    private static final Color WARNA_TABEL_HEADER = new Color(242, 229, 209);
    private static final Color WARNA_TABEL_ALT = new Color(252, 247, 240);
    private static final Color WARNA_HIJAU = new Color(94, 119, 72);
    private static final Color WARNA_ORANYE = new Color(196, 123, 44);
    private static final Color WARNA_MERAH = new Color(168, 78, 57);
    private final MenuController menuController = new MenuController();

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        setupForm();
        loadDataMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdMenu = new javax.swing.JTextField();
        txtNamaMenu = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        menuTransaksi = new javax.swing.JMenu();
        menuRiwayat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Menu - Aplikasi Kasir");
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Menu Kafe");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setText("ID Menu");

        jLabel3.setText("Nama Menu");

        jLabel4.setText("Kategori");

        txtIdMenu.setText("AUTO");
        txtIdMenu.setEnabled(false);
        txtIdMenu.addActionListener(this::txtIdMenuActionPerformed);

        txtNamaMenu.addActionListener(this::txtNamaMenuActionPerformed);

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKategori.addActionListener(this::cmbKategoriActionPerformed);

        jLabel5.setText("Harga");

        jLabel6.setText("Stok");

        txtHarga.addActionListener(this::txtHargaActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(24, 24, 24)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Menu", "Kategori", "Harga", "Stok", "Satuan"
            }
        ));
        jScrollPane2.setViewportView(tblMenu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuMaster.setText("Menu");
        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaksi");
        jMenuBar1.add(menuTransaksi);

        menuRiwayat.setText("Riwayat");
        jMenuBar1.add(menuRiwayat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMenuActionPerformed

    private void txtNamaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaMenuActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpanMenu();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        ubahMenu();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        hapusMenu();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void cmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKategoriActionPerformed
        // Kategori digunakan untuk menentukan object Makanan atau Minuman.
    }//GEN-LAST:event_cmbKategoriActionPerformed

    private void setupForm() {
        applyLayoutRapi();
        applyTemaKafe();
        txtIdMenu.setColumns(12);
        txtNamaMenu.setColumns(24);
        txtHarga.setColumns(14);
        txtStok.setColumns(14);
        cmbKategori.setModel(new DefaultComboBoxModel<>(new String[] {"Makanan", "Minuman"}));
        tblMenu.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblMenu.setModel(new DefaultTableModel(
                new Object[][] {},
                new String[] {"ID", "Nama Menu", "Kategori", "Harga", "Stok", "Satuan"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        aturLebarKolomTabel();
        tblMenu.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {
                pilihMenuDariTabel();
            }
        });
        setupNavigasi();
        resetForm();
        pack();
        setSize(UKURAN_FORM);
        setLocationRelativeTo(null);
    }

    private void applyLayoutRapi() {
        setMinimumSize(UKURAN_FORM);
        setPreferredSize(UKURAN_FORM);
        getContentPane().setPreferredSize(new Dimension(980, 680));

        setUkuranKomponen(jPanel1, 940, 215);
        setUkuranKomponen(jPanel2, 940, 330);
        setUkuranKomponen(jScrollPane2, 900, 250);
        setUkuranKomponen(txtIdMenu, 190, 28);
        setUkuranKomponen(txtNamaMenu, 275, 28);
        setUkuranKomponen(cmbKategori, 120, 28);
        setUkuranKomponen(txtHarga, 190, 28);
        setUkuranKomponen(txtStok, 190, 28);
        setUkuranKomponen(btnSimpan, 95, 32);
        setUkuranKomponen(btnUbah, 95, 32);
        setUkuranKomponen(btnHapus, 95, 32);
        setUkuranKomponen(btnReset, 95, 32);

        tblMenu.setRowHeight(26);
        layoutPanelInputMenu();
        layoutPanelDaftarMenu();
        layoutKontenUtama();
    }

    private void setUkuranKomponen(javax.swing.JComponent component, int width, int height) {
        Dimension dimension = new Dimension(width, height);
        component.setPreferredSize(dimension);
        component.setMinimumSize(dimension);
    }

    private void applyTemaKafe() {
        getContentPane().setBackground(WARNA_LATAR);
        jPanel1.setBackground(WARNA_PANEL);
        jPanel2.setBackground(WARNA_PANEL);
        jScrollPane2.getViewport().setBackground(Color.WHITE);

        jLabel1.setForeground(WARNA_COKELAT_TUA);
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 26));
        warnaiLabel(jLabel2);
        warnaiLabel(jLabel3);
        warnaiLabel(jLabel4);
        warnaiLabel(jLabel5);
        warnaiLabel(jLabel6);

        jPanel1.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(WARNA_BORDER),
                "Input Menu",
                TitledBorder.DEFAULT_JUSTIFICATION,
                TitledBorder.DEFAULT_POSITION,
                new Font("Segoe UI", Font.BOLD, 12),
                WARNA_COKELAT_TUA));
        jPanel2.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(WARNA_BORDER),
                "Daftar Menu",
                TitledBorder.DEFAULT_JUSTIFICATION,
                TitledBorder.DEFAULT_POSITION,
                new Font("Segoe UI", Font.BOLD, 12),
                WARNA_COKELAT_TUA));

        styleTextField(txtIdMenu);
        styleTextField(txtNamaMenu);
        styleTextField(txtHarga);
        styleTextField(txtStok);
        cmbKategori.setBackground(WARNA_PANEL);
        cmbKategori.setForeground(WARNA_COKELAT_TUA);

        styleButton(btnSimpan, WARNA_HIJAU, Color.WHITE);
        styleButton(btnUbah, WARNA_ORANYE, Color.WHITE);
        styleButton(btnHapus, WARNA_MERAH, Color.WHITE);
        styleButton(btnReset, new Color(238, 225, 207), WARNA_COKELAT_TUA);

        jMenuBar1.setBackground(WARNA_COKELAT_TUA);
        styleMenu(menuMaster);
        styleMenu(menuTransaksi);
        styleMenu(menuRiwayat);

        JTableHeader header = tblMenu.getTableHeader();
        header.setBackground(WARNA_TABEL_HEADER);
        header.setForeground(WARNA_COKELAT_TUA);
        header.setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblMenu.setBackground(Color.WHITE);
        tblMenu.setForeground(new Color(42, 32, 24));
        tblMenu.setGridColor(new Color(232, 218, 199));
        tblMenu.setSelectionBackground(new Color(211, 226, 196));
        tblMenu.setSelectionForeground(new Color(32, 42, 25));
        tblMenu.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component component = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    component.setBackground(row % 2 == 0 ? Color.WHITE : WARNA_TABEL_ALT);
                    component.setForeground(new Color(42, 32, 24));
                }
                setBorder(BorderFactory.createEmptyBorder(0, 8, 0, 8));
                return component;
            }
        });
    }

    private void warnaiLabel(javax.swing.JLabel label) {
        label.setForeground(WARNA_COKELAT_TUA);
    }

    private void styleTextField(javax.swing.JTextField textField) {
        textField.setBackground(Color.WHITE);
        textField.setForeground(new Color(42, 32, 24));
        textField.setBorder(BorderFactory.createLineBorder(WARNA_BORDER));
    }

    private void styleButton(javax.swing.JButton button, Color background, Color foreground) {
        button.setBackground(background);
        button.setForeground(foreground);
        button.setFocusPainted(false);
        button.setOpaque(true);
        button.setBorder(BorderFactory.createLineBorder(background.darker()));
        button.setFont(new Font("Segoe UI", Font.BOLD, 12));
    }

    private void styleMenu(javax.swing.JMenu menu) {
        menu.setOpaque(true);
        menu.setBackground(WARNA_COKELAT_TUA);
        menu.setForeground(Color.WHITE);
        menu.setFont(new Font("Segoe UI", Font.PLAIN, 13));
    }

    private void layoutPanelInputMenu() {
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtIdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(164, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(76)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(420, Short.MAX_VALUE)));

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtIdMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(31, Short.MAX_VALUE)));
    }

    private void layoutPanelDaftarMenu() {
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addContainerGap()));
    }

    private void layoutKontenUtama() {
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(16, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(32)
                                .addComponent(jLabel1)
                                .addGap(14)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(40, Short.MAX_VALUE)));
    }

    private void aturLebarKolomTabel() {
        tblMenu.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblMenu.getColumnModel().getColumn(0).setPreferredWidth(55);
        tblMenu.getColumnModel().getColumn(1).setPreferredWidth(210);
        tblMenu.getColumnModel().getColumn(2).setPreferredWidth(120);
        tblMenu.getColumnModel().getColumn(3).setPreferredWidth(120);
        tblMenu.getColumnModel().getColumn(4).setPreferredWidth(90);
        tblMenu.getColumnModel().getColumn(5).setPreferredWidth(90);
    }

    private void setupNavigasi() {
        menuMaster.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                loadDataMenu();
            }
        });
        menuTransaksi.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new FormKasir().setVisible(true);
                dispose();
            }
        });
        menuRiwayat.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new FormRiwayatTransaksi().setVisible(true);
                dispose();
            }
        });
    }

    private void loadDataMenu() {
        DefaultTableModel model = (DefaultTableModel) tblMenu.getModel();
        model.setRowCount(0);

        List<MenuItem> daftarMenu = menuController.getAllMenu();
        for (MenuItem menu : daftarMenu) {
            model.addRow(new Object[] {
                menu.getIdMenu(),
                menu.getNamaMenu(),
                toDisplayKategori(menu.getJenisMenu()),
                menu.getHarga(),
                menu.getStok(),
                menu.getSatuan()
            });
        }
    }

    private void simpanMenu() {
        try {
            String namaMenu = txtNamaMenu.getText();
            double harga = Double.parseDouble(txtHarga.getText().trim());
            int stok = Integer.parseInt(txtStok.getText().trim());
            String kategori = getKategoriTerpilih();

            boolean berhasil;
            if ("Makanan".equals(kategori)) {
                berhasil = menuController.tambahMakanan(namaMenu, harga, stok);
            } else {
                berhasil = menuController.tambahMinuman(namaMenu, harga, stok);
            }

            if (berhasil) {
                JOptionPane.showMessageDialog(this, "Menu berhasil disimpan.");
                loadDataMenu();
                resetForm();
            } else {
                tampilkanError(menuController.getLastError());
            }
        } catch (NumberFormatException e) {
            tampilkanError("Harga dan stok harus berupa angka.");
        }
    }

    private void ubahMenu() {
        try {
            int idMenu = Integer.parseInt(txtIdMenu.getText().trim());
            String namaMenu = txtNamaMenu.getText();
            double harga = Double.parseDouble(txtHarga.getText().trim());
            int stok = Integer.parseInt(txtStok.getText().trim());
            String kategori = getKategoriTerpilih();

            boolean berhasil;
            if ("Makanan".equals(kategori)) {
                berhasil = menuController.ubahMakanan(idMenu, namaMenu, harga, stok);
            } else {
                berhasil = menuController.ubahMinuman(idMenu, namaMenu, harga, stok);
            }

            if (berhasil) {
                JOptionPane.showMessageDialog(this, "Menu berhasil diubah.");
                loadDataMenu();
                resetForm();
            } else {
                tampilkanError(menuController.getLastError());
            }
        } catch (NumberFormatException e) {
            tampilkanError("Pilih data menu yang akan diubah, lalu pastikan harga dan stok berupa angka.");
        }
    }

    private void hapusMenu() {
        try {
            int idMenu = Integer.parseInt(txtIdMenu.getText().trim());
            int pilihan = JOptionPane.showConfirmDialog(
                    this,
                    "Yakin ingin menghapus menu ini?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);

            if (pilihan != JOptionPane.YES_OPTION) {
                return;
            }

            if (menuController.hapusMenu(idMenu)) {
                JOptionPane.showMessageDialog(this, "Menu berhasil dihapus.");
                loadDataMenu();
                resetForm();
            } else {
                tampilkanError(menuController.getLastError());
            }
        } catch (NumberFormatException e) {
            tampilkanError("Pilih data menu yang akan dihapus.");
        }
    }

    private void pilihMenuDariTabel() {
        int row = tblMenu.getSelectedRow();
        if (row < 0) {
            return;
        }

        txtIdMenu.setText(String.valueOf(tblMenu.getValueAt(row, 0)));
        txtNamaMenu.setText(String.valueOf(tblMenu.getValueAt(row, 1)));
        cmbKategori.setSelectedItem(String.valueOf(tblMenu.getValueAt(row, 2)));
        txtHarga.setText(String.valueOf(tblMenu.getValueAt(row, 3)));
        txtStok.setText(String.valueOf(tblMenu.getValueAt(row, 4)));
    }

    private void resetForm() {
        txtIdMenu.setText("AUTO");
        txtNamaMenu.setText("");
        txtHarga.setText("");
        txtStok.setText("");
        cmbKategori.setSelectedIndex(0);
        tblMenu.clearSelection();
        txtNamaMenu.requestFocus();
    }

    private String getKategoriTerpilih() {
        return String.valueOf(cmbKategori.getSelectedItem());
    }

    private String toDisplayKategori(String jenisMenu) {
        if ("MAKANAN".equalsIgnoreCase(jenisMenu)) {
            return "Makanan";
        }
        if ("MINUMAN".equalsIgnoreCase(jenisMenu)) {
            return "Minuman";
        }
        return jenisMenu;
    }

    private void tampilkanError(String pesan) {
        JOptionPane.showMessageDialog(this, pesan, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenu menuRiwayat;
    private javax.swing.JMenu menuTransaksi;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdMenu;
    private javax.swing.JTextField txtNamaMenu;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
